In [5]:
import glob

import cv2
import numpy as np
from matplotlib import pyplot as plt

plt.gray()

SQUARE_SIZE = 99.5  #mm
nb_vertical = 5
nb_horizontal = 7


def calibration(images: list[str]):
    # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
    objp = np.zeros((nb_horizontal * nb_vertical, 3), np.float32)
    objp[:, :2] = np.mgrid[0:nb_vertical, 0:nb_horizontal].T.reshape(-1, 2)

    # Arrays to store object points and image points from all the images.
    objpoints = []  # 3d point in real world space
    imgpoints = []  # 2d points in image plane.

    for fname in images:
        img = cv2.imread(fname)
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        ret, corners = cv2.findChessboardCorners(gray, (nb_vertical, nb_horizontal))
        
        print(ret)
        
        # If found, add object points, image points (after refining them)
        if ret:
            objpoints.append(objp)
            imgpoints.append(corners)
            # Draw and display the corners
            cv2.drawChessboardCorners(img, (nb_vertical, nb_horizontal), corners, ret)
        
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
    return mtx, dist


def undistorted(images: list[str], mtx, dist):
    undistorted_images = []
    for fname in images:
        img = cv2.imread(fname)
        h, w = img.shape[:2]
        newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx, dist, (w, h), 1, (w, h))
        dst = cv2.undistort(img, mtx, dist, None, newcameramtx)
        x, y, w, h = roi
        undistorted_images.append(dst[y:y + h, x:x + w])
    return undistorted_images

left_images = glob.glob('rspaint/left/*.png')
right_images = glob.glob('rspaint/right/*.png')
mtx, dist = calibration(left_images + right_images)

sizeimg = cv2.imread('left3.png')

left_undistorted_images = undistorted(left_images, mtx, dist)
right_undistorted_images = undistorted(right_images, mtx, dist)

results = []
print(mtx)
print(dist)


h,  w = sizeimg.shape[:2]
newcameramtx, roi = cv2.getOptimalNewCameraMatrix(mtx,dist,(w,h),1,(w,h))

print(newcameramtx)
print(roi)

False
False
True
False
True
True
True
False
True
False
False
False
False
False
False
True
False
False
True
False
[[925.46399921   0.         702.67649158]
 [  0.         938.19886469 259.91296361]
 [  0.           0.           1.        ]]
[[-0.36083455  0.14103106 -0.00837877  0.0040671   0.00562791]]
[[718.43747875   0.         715.99732372]
 [  0.         724.66275642 249.06192071]
 [  0.           0.           1.        ]]
(15, 44, 1359, 406)


<Figure size 640x480 with 0 Axes>